---
name: build-os-bookworm
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    paths:
      - '**'
      - '!README.md'
  pull_request:
    paths:
      - '**'
      - '!README.md'
  merge_group:
  workflow_dispatch:
    inputs:
      git-ref:
        description: 'Git ref (optional)'
        required: false

jobs:

  build:
    name: build
    strategy:
      fail-fast: false
      matrix:
        base_variant_name:
          - lite
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-os.yml
    secrets: inherit
    with:
      name: rpi-uc2
      base_release_name: bookworm
      base_image_variant: ${{ matrix.base_variant_name }}
      base_release_date: 2025-05-13
      base_file_release_date: 2025-05-13
      arch: arm64

  upload-zenodo:
    name: Upload to Zenodo
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.image_name }}

      - name: List downloaded files
        run: ls -R

      - name: Create Zenodo deposit
        id: create_deposit
        env:
          ZENODO_API: "https://zenodo.org/api/deposit/depositions"
        run: |
          RESPONSE=$(curl -s -X POST "$ZENODO_API" \
            --fail-with-body \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.ZENODO_ACCESS_TOKEN }}" \
            --data '{
              "metadata": {
                "title": "Raspberry Pi OS Bookworm",
                "upload_type": "dataset",
                "description": "Automated build of Raspberry Pi OS (Bookworm) for UC2",
                "creators": [{"name": "Benedict Diederich"}]
              }
            }')

          DEPOSIT_ID=$(echo $RESPONSE | jq -r '.id')
          echo "id=$DEPOSIT_ID" >> $GITHUB_OUTPUT

      - name: Upload image to Zenodo
        env:
          ZENODO_API: "https://zenodo.org/api/deposit/depositions/${{ steps.create_deposit.outputs.id }}/files"
          FILENAME: "${{ needs.build.outputs.image_name }}.img.xz"
        run: |
          curl -s -X POST "$ZENODO_API" \
            --fail-with-body \
            -H "Authorization: Bearer ${{ secrets.ZENODO_ACCESS_TOKEN }}" \
            -F "file=@$FILENAME"

      - name: Publish Zenodo record
        env:
          ZENODO_API: "https://zenodo.org/api/deposit/depositions/${{ steps.create_deposit.outputs.id }}/actions/publish"
        run: |
          curl -s -X POST "$ZENODO_API" \
            --fail-with-body \
            -H "Authorization: Bearer ${{ secrets.ZENODO_ACCESS_TOKEN }}"

      - name: Output Zenodo link
        run: echo "Zenodo record available at https://zenodo.org/record/${{ steps.create_deposit.outputs.id }}"
